on: 
  issues:
    types: [opened, reopened]

jobs:
  snyk_invite_job:
    runs-on: ubuntu-latest
    name: A job to invite a Snyk user 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: invite action step
      id: invite
      uses: ./
      with:
        snyk-org-id: "3c40230c-a886-49a6-9b57-6e3131dcf16e"
        regex-title: "Issue Trigger - .+"
        regex-email: "- Email: \\*\\*\\s*([^\\*]+)\\s*\\*\\*"
        regex-checkbox: "- \\[ \\] The checkbox"  
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
    - name: Get the output HTTP response code
      run: echo "The HTTP response code was ${{ steps.invite.outputs.http-response-code }}"
