on: 
  issues:
    types: [opened, reopened]

jobs:
  snyk_invite_job:
    runs-on: ubuntu-latest
    name: A job to invite a Snyk user 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: invite action step
      id: invite
      uses: ../
      with:
        snyk-org-id: "4a18d42f-0706-4ad0-b127-24078731fbed"
        regex-title: "Issue Trigger - .+"
        regex-email: "- Email: **([^*]+)**"
    - name: Get the output HTTP response code
      run: echo "The time was ${{ steps.invite.outputs.http-response-code }}"
